updates.pin  = [
  # sbt v2.0 plugins must be on 3.8
  { groupId = "org.scala-lang", artifactId = "scala3-library", version = "3.8." },
  # sbt v1 plugins must be on 2.12
  { groupId = "org.scala-lang", artifactId = "scala-library", version = "2.12." },
  # v5 is scala 3 only
  { groupId = "org.specs2", artifactId = "specs2-core", version = "4." }
]
